### ISSUE TITLE
mvsusieR::create_mash_prior method removed/changed

### ISSUE THREAD

**Issue by ChristopherWilks** [bhattacharya-a-bt/isotwas#1]
Hi,

First, thanks for isoTWAS, seems like an important contribution in this space! 

I noticed when trying to run the main test dataset from the helpful vignette, https://bhattacharya-a-bt.github.io/isotwas/articles/pipeline.html, that the `mvsusieR::create_mash_prior` method failed due to it no longer being in the `mvsusieR` NAMESPACE.

I ended up using a previous `mvsusieR` commit which still had that method, https://github.com/stephenslab/mvsusieR/commit/bb9084d2c3a70f63aa894cb5dd5002eee1366742
and then isoTWAS worked on the test dataset.

That method name is still referenced in the `mvsusieR` vignette so I'm not sure what their plan is:
https://stephenslab.github.io/mvsusieR/articles/prediction.html

There *does* appear to be a somewhat similar method they have now:  `create_mixture_prior`
(https://github.com/stephenslab/mvsusieR/blob/9f2891696f503d76ff2901ff3beb12be35785d20/R/mash.R#L38).  
But its signature is different enough from `create_mash_prior` that I didn't attempt to try to use it in my isoTWAS run.

Thanks,
Chris

**Comment by gk1610** [comment]
I used an older branch of mvsusie. I am able to get **mmbr::create_mash_prior** but not mvsusieR::create_mash_prior. For me, isoTWAS test dataset examples is not working. compute_isotwas calculates graphical lasso but fails at mvsusie method. If you can edit multivariate_mmbr.R file, then it would be great.

**Comment by bhattacharya-a-bt** [comment]
We've fixed the dependency issue and point to the older commit for mvsusieR, while we work with the newer functions to build out our predictive models.
