### ISSUE TITLE
Incorrect Curds and Whey model

### ISSUE THREAD

**Issue by samcoveney** [bhattacharya-a-bt/isotwas#2]
At https://github.com/bhattacharya-a-bt/isotwas/blob/501ac9e7629345e463593b01102edcacaa1b02e7/R/curds_whey.R#L48-L58 shouldn't the regression on line 49 be for yPrime, not Y? Otherwise the prediction on line 58 is for the y values in their original coordinate system, not in canonical coordinates?

**Comment by bhattacharya-a-bt** [comment]
Yes - you are correct! Thanks for catching this.
