### ISSUE TITLE
undefined symbol: dpotrf_

### ISSUE THREAD

**Issue by pvo93** [bhattacharya-a-bt/isotwas#3]
Hello,

I'm trying to install isotwas for a statistician I support at the Mayo Clinic, but I'm getting the following error. It appears that isotwas.so compiles, but I can't load it.

** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for âisotwasâ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/bigdata/bsi/s203263.Rinfrastructure/R-dev-isotwas/lib64/R/library/00LOCK-isotwas/00new/isotwas/libs/isotwas.so':
  /bigdata/bsi/s203263.Rinfrastructure/R-dev-isotwas/lib64/R/library/00LOCK-isotwas/00new/isotwas/libs/isotwas.so: undefined symbol: dpotrf_
Error: loading failed
Execution halted
ERROR: loading failed
* removing â/bigdata/bsi/s203263.Rinfrastructure/R-dev-isotwas/lib64/R/library/isotwasâ
Warning message:
In i.p(...) :
  installation of package â/tmp/RtmpYu6rsG/file2e1663948035/isotwas_0.1.0.tar.gzâ had non-zero exit status
> 

After looking over the source code with a colleague, it looks like some Lapack functions are redefined instead of including lapack.h. I've tried several workarounds including a Docker container, modifying the source code to include lapack, but I've had no luck. I even tried compiling a separate installation of R without lapack but many of the dependencies of isotwas wouldn't compile without it.

Do you have any suggestions? This is a Linux CentOS 7 server.

Thanks in advance for your time.

**Comment by pvo93** [comment]
Hello:

We've moved from CentOS7 to RHEL8, but I still run into the same issue. The .so file compiles but can't be loaded due to the undefined symbol: dpotrf_ error. I have Mayo Clinic whom I support persistently requesting to use this package, but I'm not sure where to go from here. If you could point in the right direction, it would be greatly appreciated.

Thanks,

Pat

**Comment by bhattacharya-a-bt** [comment]
This seems to be an issue with your configuration between R and LAPACK. I haven't been able to recreate this error message, but perhaps this could help? https://stackoverflow.com/questions/61765652/rcpparmadillo-undefined-symbol-dpotrf-in-travis-build
